### PR TITLE
feat: add de_formal and de_informal localizations

### PR DESCRIPTION
**Pull request by psteinroe**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

No German translation

## What is the new behavior?

Adds formal and informal translation for German.

## Additional context

For non-native speakers, here is a brief explanation of formal ("Sie") and informal ("Du") translations for the English "you" in German: https://www.gymglish.com/en/wunderbla/german-grammar/du-vs-sie

### CODE REVIEW

**Comment by psteinroe** [comment]
@thorwebdev you might be a good reviewer here 😄

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks.

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks

**Comment by riipandi** [comment]
Love it! This is a good idea to separate two kinds of language.

**Pull request merged**
