### PR TITLE
test/add tests to auth component

### PR DESCRIPTION
**Pull request by maciekgrzybek**
PR for adding unit/integration tests to the AUTH component. This PR was originally posted on the supabase/ui repo [here](https://github.com/supabase/ui/pull/307).

### CODE REVIEW

**Comment by maciekgrzybek** [comment]
hey @MildTomato, any chance that you could look at this one? :) Would be a nice starting point for some cleanup :)

**Comment by maciekgrzybek** [comment]
Any news on that? :)

**Comment by MildTomato** [comment]
ok, looks good. I'll jump in and resolve the conflicts, unless you want to?

**Comment by maciekgrzybek** [comment]
I'll do it today :) What is the status of this project anyway? Is someone actively maintaining it? If not I'm happy to co-own it ;)

**Comment by MildTomato** [comment]
@maciekgrzybek i think we'd really be open to eventually getting some co-maintainers involved 😄 
especially since we'd love to get other languages supported.

The status of this project is active, we have official documentation now in our docs.
Supabase could probably start officially laying out a roadmap for this package - and we treat the react package as the main master version that other packages copy as close as possible.

In the meantime, I think @thorwebdev, @silentworks, and myself can help keep on top of this project for now.

**Comment by silentworks** [comment]
Outdated and too many merge conflicts.

**Pull request closed without merging**
