### PR TITLE
bug icon size default change to 21px

### PR DESCRIPTION
**Pull request by rdylina**
The default styled size of the icons is 21px to make them small enough
to display properly in the button. However the SVG was setup with the
default size of 512px which causes a momentary fash of a large icon as
the page loads. This change sets the default size to 21px.

If a larger size is required in the future it can be overridden through
the styles prop just like the current implementation.

### CODE REVIEW

**Comment by rdylina** [comment]
@MildTomato @thorwebdev @silentworks 

Good evening, this is a pull request for your review. This should help fix #151 and #101 . As has been reported by a few people the default icon sizes are excessive and, in some implementations, result in a full-size 512px flash during page render prior to the default icon styles being applied. I would like to merge this request that modifies the icon size down, then, they can be upsized through styling if needed. This will result in significantly fewer cumulative layout changes and obviously does away with the large icon flash.

Thank you!

**Comment by silentworks** [comment]
Hey @rdylina thank you for this PR. I will get it merged in soon but will add the other packages to it also as they all have these same icons in them. That's the Solid and Svelte packages.

**Comment by rdylina** [comment]
> Hey @rdylina thank you for this PR. I will get it merged in soon but will add the other packages to it also as they all have these same icons in them. That's the Solid and Svelte packages.

Oops, I didn't even think to check the other packages. Want me to go through and add them to my PR?

**Comment by silentworks** [comment]
Yeah that would be appreciated.

**Comment by rdylina** [comment]
> Yeah that would be appreciated.

All done, some of them were specified without units "512" instead of "512px". I made sure they are all unit specific in px while I was at it.

Re-synced with forked branch as well to ensure there were no collisions. Should be good to go.

**Comment by silentworks** [comment]
Thank you for this PR @rdylina. A release should be out shortly with this fix.

**Pull request merged**
